### ISSUE TITLE
Área de participação

### ISSUE THREAD

**Issue by eduardozulian** [campanhacompleta/publico#1]
Nós definimos uma área de participação que, inicialmente, poderá contar com destaques como:
- Consultas públicas
- Comunidades interativas
- Sistema de doações
- Transparência

Ideias de como podemos fazer isso de forma genérica, e não atendendo apenas a um cliente?

**Comment by jpmehl** [comment]
Não compreendi o problema. Todas as soluçòes propostas já são genéricas para uso amplo.

**Comment by eduardozulian** [comment]
Podemos tranquilamente então usar uma área específica de widgets?

**Comment by eduardozulian** [comment]
Definido como uma área de widgets (chamada _Social Engagement Area_) em fbfa3537356d7724f7fbe27553344332b685a70a
