### ISSUE TITLE
Imagem de cabeçalho: ela não completa o site inteiro

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/publico#23]
Com resolução de 1920x1080 sobra um espaço em branco na direita do site.

**Comment by eduardozulian** [comment]
Talvez o ideal seja aumentarmos esse tamanho para 1920 mesmo. Ah, e centralizar a imagem.

**Comment by jpmehl** [comment]
Ótimo
Em 25/09/2015 23:52, "Eduardo Zulian" notifications@github.com escreveu:

**Comment by eduardozulian** [comment]
Agora, nosso tamanho é de 1920px x 360px, e a imagem é centralizada. Para imagens menores, o WP se encarregará de estica-las até a proporção definida.
