### ISSUE TITLE
Agenda: ajustar estilo e mapear informações

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/publico#24]
É preciso ajustar o estilo da agenda tanto no widget de capa e internas quanto na página com todos os eventos. 
Também não está puxando todas as informações, ter a apresentação de detalhes como Local, data e hora bem separados é importante.

**Comment by eduardozulian** [comment]
Já tratado em #8.

A ideia é usarmos o Events Manager e não mais a questão embarcada da agenda. Sendo assim, o tratamento da informação é dado através do plugin. Consegue ver isso, @jpmehl?

**Comment by jpmehl** [comment]
To sabendo, mas os testes que fiz já não são neste plugin?
Em 25/09/2015 13:17, "Eduardo Zulian" notifications@github.com escreveu:

**Comment by eduardozulian** [comment]
Não, esse é o embarcado. É preciso instalar o Events Manager no ambiente de testes.
