### ISSUE TITLE
Parlamentares: Criar Plugin "parlamentar"

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/publico#25]
Conforme dialogado no https://github.com/campanhacompleta/prj/issues/7, é preciso criar este plugin para podemos apresentar a página dos parlamentares: 
Vamos começar com estes dados, conforme layout: 

Dados gerais

```
Nome
Nome completo do parlamentar
Data de nascimento
Naturalidade
Estado civil
Ocupação
Escolaridade
Biografia
Links externos (Wikipedia, Facebook, Twitter etc)
```

Dados para contato

```
Email
Endereço
Telefone
```

Dados de transparência

```
Link para prestação de contas ao TRE
Link para prestação de contas do mandato
Equipe do mandato
```

**Comment by eduardozulian** [comment]
Fechado. Transferir issues para http://github.com/campanhacompleta/parlamentar
