### ISSUE TITLE
Contato: Criar área de contato

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/publico#27]
a Página de contato aparentemente não está criada. o /contato está abrindo uma página em branco.

**Comment by eduardozulian** [comment]
Sugiro aproveitarmos a mudança mais radical na relação com o tema pra adicionar um plugin específico para isso, como o [ContactForm 7](https://wordpress.org/plugins/contact-form-7/).

@jacsop, como você avalia isso?

**Comment by jacsonp** [comment]
Este plugin já está disponível, a página de contato se eu não me engano, tem que configurar o plugin de contato que tem na plataforma

**Comment by eduardozulian** [comment]
@jpmehl, vamos usar o ContactForm 7 então? Consegue fazer um teste e ver se ele funciona? Assim evitamos de criar uma área desnecessária para o tema.

**Comment by jpmehl** [comment]
Fiz os testes, mas por algum motivo que desconheço ele não funciona no /contato, mas conseguir fazer funcinoar trocando a url para /formulario-de-contato/
Tem um estilo básico pra ajustar apenas e tá resolvido.

Mas fazendo uma provocação aqui pra pensarmos pra frente, nunca gostei de formulários de contato que mandam as coisas por e-mail, uma ferramenta mais robusta, que sistematize os contatos seria ótimo.

**Comment by eduardozulian** [comment]
`entre-em-contato` parece ser uma URL melhor.

Sobre problemas de estilos, abre umas issues para que eu possa trata-las separadamente, ok?

E registra essa provocação geral também! :D

**Comment by jacsonp** [comment]
para que aparece a configuração página de contato, precisa ter um arquivo tpl-contato.php
no tema

**Comment by eduardozulian** [comment]
Podemos bater o martelo e usar o ContactForm 7 mesmo? Se sim, eu fecho esse tópico.

**Comment by jpmehl** [comment]
Fecha
Em 25/09/2015 13:15, "Eduardo Zulian" notifications@github.com escreveu:
