### ISSUE TITLE
Social Engagment área: Precisa melhorar o estilo

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/publico#28]
Precisamos de uma solução melhor para o estilo desta área. 
Inicialmente tinhamos previsto um ícone e um pequeno texto que delimitasse o que seria este bloco de informações, acho importante ele existir. 
No que tange cada widgets, talvez a melhor solução seja utilizar banners com texto mesmo, daria mais autonomia para cada projeto.

**Comment by eduardozulian** [comment]
Sobre os widgets, fica a critério do projeto como usá-los.

Agora, para o estilo, vou seguir a ideia do layout. Minha grande preocupação com os ícones é que nós não possuímos meios hoje de cadastra-los para que sejam usados tanto para os títulos dos widgets quando para áreas que englobam widgets (como no caso de Participação).

Como nenhum ícone ainda foi definido (ver #5), essa área se mantém nebulosa e vale uma issue separada.

**Comment by eduardozulian** [comment]
Lembrando também que a issue #12 tem a ver com os estilos desta área.
