### ISSUE TITLE
Sem hover no menu do footer

### ISSUE THREAD

**Issue by jacsonp** [campanhacompleta/publico#49]
Hover quase imperceptível. Em monitor ruim, nem da para ver mesmo

**Comment by eduardozulian** [comment]
@thalitasejanes, alguma ideia pra gente? Isso tem relação total com a issue #12

**Comment by thalitasejanes** [comment]
@eduardozulian inicialmente eu tinha pensado no rosa ( #aa2446), mas isso que o jac tá apresentando na questao #12, acho que vamos ter que puxar mais uma cor, pois o cinza (#ccc) não oferece constraste algum...

**Comment by thalitasejanes** [comment]
também rabaixei o pŕoprio roxo no 0to255 (#7c7abd)

**Comment by eduardozulian** [comment]
Vou fazer isso automaticamente pelo .scss, mas a solução é temporária. Quando formos analisar o uso do tema para outros casos (vide #2), isso provavelmente precisará melhorar.
