### ISSUE TITLE
Está aparecendo 2 eventos

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/publico#52]
No admin, para adicionar um evento, estão aparecendo 3 opções: 
Evento
Evento
Evento recorrente

Aparentemente o correto é o segundo, o recorrente não me aprofundei.

**Comment by eduardozulian** [comment]
Não entendi, @jpmehl. 

Mas aviso que evento recorrente é um evento recorrente, que se repete de tanto em tanto.

**Comment by jpmehl** [comment]
Já flagrei o lance do evento recorrente. 
Mas a duplicidade parece que era coisa da plataforma, então tá ok
