### ISSUE TITLE
Botão de compartilhar via FB

### ISSUE THREAD

**Issue by anapaulabrasa** [campanhacompleta/publico#56]
Inserção de botão em posts para compartilhar via facebook, GOOGLE + e Twitter

**Comment by anapaulabrasa** [comment]
Temos um retorno aqui? Cliente está pressionando, @eduardozulian e @jpmehl

**Comment by jpmehl** [comment]
estamos testando em http://novocnpc.beta.redelivre.org.br mas até agora tá
dando problema

Em 7 de março de 2016 16:13, anapaulabrasa notifications@github.com
escreveu:

> Temos um retorno aqui? Cliente está pressionando, @eduardozulian
> https://github.com/eduardozulian e @jpmehl https://github.com/jpmehl
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/campanhacompleta/publico/issues/56#issuecomment-193401834
> .

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9221-1909

**Comment by anapaulabrasa** [comment]
Não podemos utilizar a mesma solução que foi usada em Flacso? @jpmehl @eduardozulian

**Comment by eduardozulian** [comment]
Tá feito.

Eu vou abrir uma nova ideia na Rede Livre para que isso vire um plugin dentro da Rede Livre. Acho que esse tipo de funcionalidade não deveria estar dentro de um tema.

**Comment by eduardozulian** [comment]
Criado em https://github.com/redelivre/redelivre/issues/67
