### ISSUE TITLE
Abrir em nova página as redes sociais do rodapé

### ISSUE THREAD

**Issue by anapaulabrasa** [campanhacompleta/publico#57]
Abrir em nova página as redes sociais do rodapé quando o usuário clica nos ícones, para que ele não saia completamente do site.

**Comment by eduardozulian** [comment]
Essa é uma questão antiga e que divide opiniões. Eu prefiro deixar como está (ainda que sempre perca essa batalha).

**Comment by jpmehl** [comment]
Sim @eduardozulian , é uma questão antiga. Já fui convencido em outra ocasiões, mas considerando que só usuários avançados que sabem gerenciar este tipo de opção no navegador, minha posição é de que a gente deixe a opção para que o usuário feche a aba se não quiser mais estar no site, mas defendo que abra em outra página, pois acho bem melhor para o usuário final, além de ser um pedido de basicamente todos os usuários que tivemos contato ao longo do tempo.

**Comment by anapaulabrasa** [comment]
Reforço o que o @jpmehl coloca. É uma demanda constante dos usuários a abertura de uma nova aba quando o internauta clica no ícone da rede social para que o próprio sistema não empurre os visitantes pra fora de seu site.

**Comment by eduardozulian** [comment]
Como eu disse, batalha perdida. Mas hoje eu dia me sinto mais tranquilo com isso. :smile: 

Mudemos então!

**Comment by eduardozulian** [comment]
Relacionado: #30

**Comment by eduardozulian** [comment]
Isso pode ser feito pelo próprio usuário: https://codex.wordpress.org/WordPress_Menu_User_Guide#Customising_Menu_Items

Atualizei o README.md com as novas formas de se fazer isso.
