### ISSUE TITLE
Inserir tumbnail(print) do vídeo na página interna da categoria vídeos

### ISSUE THREAD

**Issue by jpmehl** [campanhacompleta/publico#61]
Para que melhore a visualidade da pesquisa dos vídeos, deve-se permitir a)imagem destacada b)puxar tumbnail direto do youtube

**Comment by eduardozulian** [comment]
Agora no arquivo de videos há um visualizador automatico do primeiro video cadastrado no conteúdo do post. Fiz uns testes aqui e tudo correu bem e achei melhor do que o thumbnail.
