### ISSUE TITLE
Cálculo erroneo da idade em Parlamentares

### ISSUE THREAD

**Issue by anapaulabrasa** [campanhacompleta/publico#62]
@eduardozulian Em Parlamentares, a idade não está de acordo com data de nascimento cadastrada.

![parlament](https://cloud.githubusercontent.com/assets/2422926/13531976/f90f05e4-e207-11e5-8fea-d25da6a23de7.png)

**Comment by eduardozulian** [comment]
Fechado em https://github.com/campanhacompleta/parlamentar/commit/7bfc7b0e520fb328f9123112d52354826b4dd6c9

@anapaulabrasa, a maioria dos assuntos relacionados a parlamentares é gerenciada no https://github.com/campanhacompleta/parlamentar/ :)

Assim que testar, pode fechar aqui se tiver tudo ok! :facepunch:
