### ISSUE TITLE
Box Data de nascimento não funciona

### ISSUE THREAD

**Issue by anapaulabrasa** [campanhacompleta/publico#63]
No campo Data de nascimento, em Parlamentar, não é possível editar os dados na caixinha de data. 
@eduardozulian Seleciono dia, mês ou ano pela caixinha, mas ela não registra. 

![boxdata](https://cloud.githubusercontent.com/assets/2422926/13532155/ba54da12-e208-11e5-9d64-f1233644e539.png)

**Comment by eduardozulian** [comment]
@anapaulabrasa, não consegui reproduzir o problema. 

Lembrando que é necessário sempre clicar no dia para que a mudança seja registrada.

Abaixo, um gif que mostra como testei:

![datepicker](https://cloud.githubusercontent.com/assets/1136160/13618689/4c391282-e564-11e5-8c1f-130bfa53697e.gif)

**Comment by anapaulabrasa** [comment]
fechou, Zulian! Era a questão de finalizar com o dia mesmo.
